spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/test_db
    username: postgres
    password: 123456
    hikari:
      initialization-fail-timeout: 60000  # đợi 60s


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

mybatis:
  type-aliases-package: com.java.TrainningJV.models
  mapper-locations: classpath:mapper/*.xml
