server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # hoặc "validate", "create", "create-drop"
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


mybatis:
  type-aliases-package: com.java.TrainningJV.models
  mapper-locations: classpath:mapper/*.xml